services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    restart: unless-stopped
    ports:
      - "8088:8080"
    volumes:
      - privatebin-data:/srv/data

volumes:
  privatebin-data: